apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    db: postgres-service
spec:
  selector:
    db: postgres-db
  clusterIP: None
  ports:
    - port:  5432
      targetPort:  5432