apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres-deployment
  labels: 
    db: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      db: postgress-db
  template:
    metadata:
      labels:
        db: postgress-db
    spec:
      containers:
        - name: postgress-db
          image: postgres:14.19-alpine3.21
          ports:
          - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: trainingdb
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}


    